services:
  - type: web
    name: his-lipe-core
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: >
      gunicorn backend.app_lipe_core:app
      -k uvicorn.workers.UvicornWorker
      -b 0.0.0.0:$PORT -w 2 --timeout 120
    envVars:
      - key: ALLOW_ORIGINS
        value: "*"
